# Enable debug logs.
debug: true
# Enable trace logs.
#trace: true 
spring:
  datasource:
    # From the h2 docs: To keep the content of an in-memory database as long as the virtual machine is alive, use DB_CLOSE_DELAY=-1
    # From the spring docs: If, for whatever reason, you do configure the connection URL for an embedded database, 
    # take care to ensure that the database's automatic shutdown is disabled. If you use H2, you should use 
    # DB_CLOSE_ON_EXIT=FALSE to do so.       
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
