# Enable debug logs.
debug: true
# Enable trace logs.
#trace: true 
spring:
  datasource:
    initialize: true
    # From the h2 docs:To keep the content of an in-memory database as long as the virtual machine is alive, use DB_CLOSE_DELAY=-      
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1


#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.path=/myconsole
#spring.h2.console.enabled=true
#spring.datasource.schema=schema.sql
#spring.datasource.data=data.sql